version: '3'
services:
  bot:
    build: 
        context: .
        dockerfile: src/Miki/Dockerfile
        args:
          private_nuget_pat: ${PRIVATE_NUGET_PAT}
    container_name: "miki"
    env_file:
        - .env
    network_mode: host